id = "doom-one-theme"
name = "Doom One"
version = "1.0.0"
schema_version = 1
authors = ["bashln", "Leo"]
description = "A faithful and vibrant port of the Doom One theme from Doom Emacs to Zed."
repository = "https://github.com/bashln/zed-doom"
